### ISSUE TITLE
Possible to Overlay a Tap Recognizer?

### ISSUE THREAD

**Issue by alexgpark** [MichMich/XMCircleGestureRecognizer#3]
Loving this and it's working great so far! Thank you MichMich!

Just one challenge - I have tried to add a Tap Gesture Recognizer on top but it does not get recognized.

I have also tried to add a Button, and it also does not get recognized.

Any tips on how to workaround either of these?

**Comment by MichMich** [comment]
Hi Alex,

A button should be working. Make sure you put the button _above_ the view with the XMCircleGestureRecognizer, and not inside that view.

Adding a Tap Gesture to the same view as the XMCircleGestureRecognizer might indeed not work, since these two would interfere.

**Comment by alexgpark** [comment]
Ah, so to make sure I understand correct - the area with XMCircleGestureRecognizer cannot have a button within it? :\

Here's what I'm trying to build with your library: http://i.imgur.com/LaT7y71.png

Got everything but the Play button in the middle working! Yargh!

**Comment by MichMich** [comment]
It's absolutely possible. But you need to make sure the button is not a subview of the view that has the XMCircleGestureRecognizer.

**Comment by alexgpark** [comment]
You're absolutely right, I just did that and it works like a charm. Thanks again MichMich! Masterful job!

**Comment by MichMich** [comment]
Good to hear!
